language: ruby
cache: bundler

rvm:
  - 2.3.1

addons:
  postgresql: '9.4'

before_script:
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.sample config/secrets.yml

script:
  - 'bundle exec rake db:create'
  - 'bundle exec rake db:migrate'

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzu.com
    on_failure: change
    on_success: never

